---
title: "gather"
author: "Lavinia Teodorescu"
date: "10/17/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, message = FALSE)
library(tidyverse)
library(tidytext)
library(readr)
library(readxl)
library(stringr)
library(leaflet)
library(maptools)
library(plotly)
library(rstanarm)

library(shiny)
library(shinythemes)

library(ggplot2)
library(ggthemes)
library(gganimate)
library(plotly)
library(sf)
library(rstanarm)
library(gtsummary)
library(broom.mixed)
library(gt)

```


```{r}
country_by_continent <- read_csv("raw_data/data.csv") %>%
  rename(ISO3 = "Three_Letter_Country_Code")
saveRDS(country_by_continent, file = "shiny-app/data/country_by_continent.rds")
country_by_continent <- readRDS(file = "shiny-app/data/country_by_continent.rds")

# This dataset contains countries, and their respective continent and country codes.

communist_countries_2020 <- read_csv("raw_data/csvData.csv")
saveRDS(communist_countries_2020, file = "shiny-app/data/communist_countries_2020.rds")
communist_countries_2020 <- readRDS(file = "shiny-app/data/communist_countries_2020.rds")

# This dataset contains all countries that are communist at the moment (2020)

parliament_type <- read_csv("raw_data/idea_export_35_5f8a138aec279.csv")
saveRDS(parliament_type, file = "shiny-app/data/parliament_type.rds")
parliament_type <- readRDS(file = "shiny-app/data/parliament_type.rds")

# This dataset contains the parliament type of each country and other data
# regarding the political structure (can't remember what I'm using this for)

employment_female <- read_csv("raw_data/recent-ILO-LFP.csv")
saveRDS(employment_female, file = "shiny-app/data/employment_female.rds")
employment_female <- readRDS(file = "shiny-app/data/employment_female.rds") 

# This dataset contains percentage of female population ages 15+ that
# participated in labor force

employment_sector <- read_csv("raw_data/EMP_TEMP_SEX_INS_NB_A.csv")
saveRDS(employment_sector, file = "shiny-app/data/employment_sector.rds")
employment_sector <- readRDS(file = "shiny-app/data/employment_sector.rds")

# This dataset contains the division of labor based on sector (private, public,
# total) and sex (f, m, total)

ilostat_2020_11_13_2 <- read_csv("raw_data/ilostat-2020-11-13-2.csv")
saveRDS(ilostat_2020_11_13_2, file = "shiny-app/data/employment_sex_sector.rds")
employment_sex_sector <- readRDS(file = "shiny-app/data/employment_sex_sector.rds")

# Same as the one one above, but with more data/ notations. I need to delete one
# of them
# https://www.ilo.org/shinyapps/bulkexplorer58/?lang=en&segment=indicator&id=EES_TEES_SEX_INS_NB_A

employment_position <- read_csv("raw_data/ilostat-2020-11-13-3.csv")
saveRDS(employment_position, file = "shiny-app/data/employment_position.rds")
employment_position <- readRDS(file = "shiny-app/data/employment_position.rds")

# Female share of employment in managerial positions (%) - senior/ total
# managerial

employment_pay <- read_csv("raw_data/ilostat-2020-11-13-4.csv")
saveRDS(employment_pay, file = "shiny-app/data/employment_pay.rds")
employment_pay <- readRDS(file = "shiny-app/data/employment_pay.rds")

# Average hourly earnings of employees by sex in local currency, by position

comm_years <- read_csv("raw_data/Comm_Years.csv")
saveRDS(comm_years, file = "shiny-app/data/comm_years.rds")
comm_years <- readRDS(file = "shiny-app/data/comm_years.rds")

gender_indicators_health <- read_csv("raw_data/Gender_Indicators_Report-3.csv") %>%
rename(health_decision_question = "Series Name") %>%
rename("year_2011" = "2011 [YR2011]") %>%
  rename("year_2012" = "2012 [YR2012]") %>%
  rename("year_2013" = "2013 [YR2013]") %>%
  rename("year_2014" = "2014 [YR2014]") %>%
  rename("year_2015" = "2015 [YR2015]") %>%
  rename("year_2016" = "2016 [YR2016]") %>%
  rename("year_2017" = "2017 [YR2017]") %>%
  rename("year_2018" = "2018 [YR2018]") %>%
mutate(health_decision_maker = ifelse(health_decision_question == "Decision maker about a woman's own health care: mainly husband (% of women age 15-49)", "husband", "other")) %>%
mutate(health_decision_maker = ifelse(health_decision_question == "Decision maker about a woman's own health care: mainly wife (% of women age 15-49)", "wife", health_decision_maker))  %>%
mutate(health_decision_maker = ifelse(health_decision_question == "Decision maker about a woman's own health care: someone else (% of women age 15-49)", "someone_else", health_decision_maker))

saveRDS(gender_indicators_health, file = "shiny-app/data/gender_indicators_health.rds")
gender_indicators_health <- readRDS(file = "shiny-app/data/gender_indicators_health.rds")


```


```{r}
women_in_parliament_2008 <- read_excel("raw_data/cpdsIIc/Women in Parliament UPDATED 2008.xls")
  
CPDS_1960_2018 <- read_excel("raw_data/CPDS_1960-2018_Update_2020.xlsx")

post_comm_list <- read_excel("raw_data/cpdsIIc/Women in Parliament UPDATED 2008.xls") %>%
  mutate(post_comm = "TRUE") %>%
  select(country, post_comm) %>%
  distinct() %>%
right_join(CPDS_1960_2018, by = "country") %>%
  mutate(post_comm = ifelse(is.na(post_comm), FALSE, TRUE))
  
  saveRDS(post_comm_list, file = "shiny-app/data/post_comm_list.rds")
```


```{r}
post_comm_list %>%
  rename("year" = 'year...1') %>%
  filter(year == 2018) %>%
  ggplot(aes(x = reorder_within(country, womenpar, womenpar), y = womenpar, color = post_comm)) +
  geom_point() +
  facet_wrap(~post_comm, drop = TRUE, scales = "free_x") +
  scale_x_reordered() +
    theme_linedraw() +
    theme(panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey"),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(color = "grey", fill = NA)) +
  scale_color_discrete(name = "Communist Status", 
                       labels = c("Never Communist", "Post-Communist"))+
    labs(title = "Women in Parliament: Never Communist v. Post- Communist Countries", 
          x = "OECD Countries", 
          y = "Percentage of Women in Parliament", 
          caption = "\n  \n Source: CPDS") +
    theme(axis.text.x = element_text(angle=30))

# To have one boxplot w/ post comm, never comm and currently comm

```


```{r}

# country_by_continent <- readRDS(file = "shiny-app/data/country_by_continent.rds")
# country_by_continent <- country_by_continent %>%
#  rename(country_code = "Three_Letter_Country_Code") %>%
#  select(country_code, Continent_Name)

# employment_sex_sector_edit <- employment_sex_sector %>%
#  select(ref_area, ref_area.label, sex, classif1, time, obs_value) %>%
#  rename("country_code" = "ref_area") 

# employment_sex_continent <- left_join(employment_sex_sector_edit, country_by_continent, by = "country_code") 

# employment_sex_continent %>%
#  filter(sex == "SEX_F") %>%
#  filter(classif1 == "INS_SECTOR_PUB") %>%
#  filter(Continent_Name %in% c("Asia", "Africa", "North America", "Oceania", "South America", "Europe")) %>%
#  filter(!is.na(obs_value)) %>%
#  ggplot(aes(x = Continent_Name, y = obs_value)) +
#  geom_col()
```


```{r}
graph_1 <- employment_female %>%
  rename("female_percentage" = "Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)") %>%
  left_join(post_comm_list, by = c("Code" = "iso")) %>%
  select("Entity", "Code", "Year", "female_percentage", "post_comm") %>%
  left_join(employment_sector, by = c("Code" = "ref_area", "Year" = "time")) %>%
  select("Entity", "Code", "Year", "female_percentage", "post_comm", "sex", "classif1", "obs_value") %>%
  left_join(country_by_continent, by = c("Code" = "ISO3")) %>%
  select("Entity", "Code", "Year", "female_percentage", "post_comm", "sex", "classif1", "obs_value", "Continent_Name") %>%
  unique() 


graph_1 <- graph_1 %>%
  mutate(post_comm = ifelse(Code %in% c("CHN", "VNM", "LAO", "CUB", "PRK"), "NOW", post_comm)) %>%
  mutate(post_comm = ifelse(is.na(post_comm), "FALSE", post_comm)) %>%
  # replace_na(post_comm, "FALSE")
  pivot_wider(names_from = c("sex", "classif1"), values_from = "obs_value") %>%
  #group_by("Entity", "Year", "classif1") %>%
  select(-"NA_NA") %>%
  mutate(percentage_female_total = SEX_F_INS_SECTOR_TOTAL/SEX_T_INS_SECTOR_TOTAL*100) %>%
    mutate(percentage_female_private = SEX_F_INS_SECTOR_PRI/SEX_T_INS_SECTOR_PRI*100) %>%
    mutate(percentage_female_public = SEX_F_INS_SECTOR_PUB/SEX_T_INS_SECTOR_PUB*100)
saveRDS(graph_1, file = "shiny-app/data/graph_1.rds")

graph_1 %>%
 # filter(!is.na(percentage_female_total)) %>%
  # filter(Year == "2000") %>%
  ggplot(aes(x = post_comm, y = female_percentage, color = post_comm)) +
  geom_point() +
  geom_smooth(method = "lm")
  
```

```{r}


graph_2 <- graph_1 %>%
  filter(Year == "2017")

fit_1 <- stan_glm(formula = female_percentage ~ post_comm + Continent_Name, 
         data = graph_2, 
         family = gaussian(),
         refresh = 0)
write_rds(fit_1, "fit_1.rds")
fit_table <- tbl_regression(fit_1, 
                                       exponentiate = TRUE) 

post_fit <- posterior_epred(fit_1)  %>%
  as_tibble 

#Add GDP?
```



```{r}

map_post_comm <- readRDS(file = "shiny-app/data/post_comm_list.rds") %>%
  distinct(country, .keep_all = TRUE)%>%
  rename(ISO3 = "iso")

data(wrld_simpl)

saveRDS(wrld_simpl, file = "shiny-app/data/wrld_simpl.rds") 

world_simple_comm <- wrld_simpl@data %>%
  left_join(map_post_comm, by = "ISO3")

map_post_comm <- readRDS(file = "shiny-app/data/post_comm_list.rds") %>%
  distinct(country, .keep_all = TRUE) %>%
  rename(ISO3 = "iso")

# In your previous code, you assigned only the data table from wrld_smpl to world_simple_comm. You need the data table and the polygons! So, first create an identical copy of wrld_simpl:

world_simple_comm <- wrld_simpl

# Then edit just the data table of that identical copy:

world_simple_comm@data <- world_simple_comm@data %>%
  left_join(map_post_comm, by = "ISO3")

# Now, world_simple_comm has an updated data table AND the polygons, and can be used in leaflet:


  binpal <- colorBin("Blues", world_simple_comm$gov_right1, 6, pretty = FALSE)
  
map <- leaflet(world_simple_comm) %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
    color = ~binpal(gov_right1)) %>%
  addProviderTiles(providers$CartoDB.Positron)
map

```

```{r}
employment_female %>%
  
  # The initial column title is to long and I can't seem to be able to put it on
  # two lines because rename() stops working.
  rename("female_percentage" = "Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)") %>%
  group_by(Entity) %>%
  summarize(avg = mean(female_percentage), .groups = "drop") %>%
  filter(str_detect(Entity, "^B")) %>%
  
  # This filters the Entity column to find all names that start with a capital
  # B. str_detect is part of the stringr package.
  
ggplot(mapping = aes(x = reorder_within(Entity, within = avg, by = avg), y = avg)) +
  geom_point() +
  scale_x_reordered() +
    theme_linedraw() +
    theme(panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey"),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(color = "grey", fill = NA)) +
    theme(axis.text.x = element_text(angle=30)) +
     labs(title = "Women in the Workforce: By country (letter B)", 
          x = "Countries", 
          y = "Percentage of Women in the Workforce", 
          caption = "\n  \n Source: Inter-Parliamentary Union") 

# This is a combination of themes that I did in the past and really enjoyed, so
# decided to copy it here as well. reorder_withing and scale_x_reorder helped me
# reorger values n the x axis based on the values on the y axis.

```


```{r}

average_employment <- graph_1 %>%
  group_by(Entity) %>%
  drop_na(percentage_female_total) %>%
  mutate(mean_percentage_total = mean(percentage_female_total)) %>%
  rename(ISO3 = "Code")
  
saveRDS(average_employment, file = "shiny-app/data/average_employment.rds")

# In your previous code, you assigned only the data table from wrld_smpl to world_simple_comm. You need the data table and the polygons! So, first create an identical copy of wrld_simpl:

world_simple_employment <- wrld_simpl

# Then edit just the data table of that identical copy:

world_simple_employment@data <- world_simple_employment@data %>%
  left_join(average_employment, by = "ISO3")

saveRDS(world_simple_employment, file = "shiny-app/data/world_simple_employment.rds")

# Now, world_simple_comm has an updated data table AND the polygons, and can be used in leaflet:

binpal <- colorBin("Reds", world_simple_employment$mean_percentage_total, 9, pretty = FALSE)
  
map_employment <- leaflet(world_simple_employment) %>%
  addPolygons(stroke = FALSE, smoothFactor = 1, fillOpacity = 1,
    color = ~binpal(mean_percentage_total)) %>%
  addProviderTiles(providers$CartoDB.Positron)

map_employment


```



```{r}

post_comm_list %>%
  rename("year" = 'year...1') %>%
  filter(year == 2018) %>%
  ggplot(aes(x = post_comm, y = womenpar, color = post_comm)) +
  geom_boxplot() +
  scale_x_reordered() +
    theme_linedraw() +
    theme(panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey"),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(color = "grey", fill = NA)) +
  scale_color_discrete(name = "Communist Status", 
                       labels = c("Never Communist", "Post-Communist"))+
    labs(title = "Women in Parliament: Never Communist v. Post- Communist Countries", 
          x = "OECD Countries", 
          y = "Percentage of Women in Parliament", 
          caption = "\n  \n Source: CPDS") +
    theme(axis.text.x = element_text(angle=30))

```

```{r}

# PAGE 1: Map

comm_years_leaf <- comm_years %>%
  left_join(graph_1, by = c("country" = "Entity"))

comm_years_leaf <- comm_years_leaf %>%
  select("country", "year_first", "year_last", "Code", "Continent_Name") %>%
  unique() %>%
  rename(ISO3 = "Code") %>%
  slice(-1)

# comm_years_leaf <- comm_years_leaf %>%
#  ifelse(country == "Democratic Republic of Congo", ISO3 = "COD", ISO3)
#  rename([27][4] = "COD")

  comm_years_leaf[27,4] <- "KGZ"
  comm_years_leaf[41,4] <- "COD"
  comm_years_leaf[49,4] <- "GRD"
  comm_years_leaf[54,4] <- "BIH"
  comm_years_leaf[27,5] <- "Asia"
  comm_years_leaf[41,5] <- "Africa"
  comm_years_leaf[49,5] <- "North America"
  comm_years_leaf[54,5] <- "Europe"
  
# I couldn't think of another way to rename this, so I just went into the table
# and hand-renamed them
    


comm_years_leaf <- comm_years_leaf %>%
  right_join(country_by_continent, by = "ISO3")

comm_years_leaf <- comm_years_leaf %>%
  select(Country_Name, year_first, year_last, ISO3, Continent_Name.x) %>%
  unique() 
comm_years_leaf$year_first <-  ifelse(is.na(comm_years_leaf$year_first), "0", comm_years_leaf$year_first)
comm_years_leaf$year_last <-  ifelse(is.na(comm_years_leaf$year_last), "0", comm_years_leaf$year_last)

saveRDS(comm_years_leaf, file = "shiny-app/data/comm_years_leaf.rds")

comm_years_leaf <- comm_years_leaf %>%
mutate(communist = ifelse(year_first <= 1979 & 1979 <= year_last, "yes", "no"))

# comm_years_leaf$Country_Name
world_simple_timeline <- wrld_simpl

# Then edit just the data table of that identical copy:

world_simple_timeline@data <- world_simple_timeline@data %>%
  left_join(comm_years_leaf, by = "ISO3")
world_simple_timeline@data$communist <- 
  ifelse(is.na(world_simple_timeline@data$communist), 
         "no", 
         world_simple_timeline@data$communist)
  

saveRDS(world_simple_timeline, file = "shiny-app/data/world_simple_timeline.rds")

# Now, world_simple_comm has an updated data table AND the polygons, and can be used in leaflet:

factpal <- colorFactor(c("red", "yellow"), world_simple_timeline$communist)
  
map_timeline <- leaflet(world_simple_timeline) %>%
  addPolygons(stroke = FALSE, smoothFactor = 1, fillOpacity = 1,
    color = ~factpal(communist)) %>%
  addProviderTiles(providers$CartoDB.Positron)

map_timeline

```

```{r}

# PAGE 3

gender_indicators_health_graph <- gender_indicators_health %>%
  rename(country = "Country Name") %>%
  rename(ISO3 = "Country Code") %>%
  pivot_longer(cols = year_2011:year_2018, names_to = "year", values_to = "percentage") %>%
  filter(percentage != "..") %>%
  select(-c("Series Code", "2019 [YR2019]", "2020 [YR2020]"))
  gender_indicators_health_graph$percentage <- as.double(gender_indicators_health_graph$percentage) 
  
gender_health_graph <- gender_indicators_health_graph %>%
  group_by(country, year, health_decision_maker) %>%
  mutate(average = mean(percentage)) %>%
  left_join(comm_years_leaf, by = "ISO3") %>%
  left_join(country_by_continent, by = "ISO3") %>%
  mutate(communist = ifelse(year_first !=  "0", TRUE, FALSE)) %>%
  filter(Continent_Name == "Asia")
  
saveRDS(gender_health_graph, file = "shiny-app/data/gender_health_graph.rds") 

gender_health_graph %>%
  ggplot(aes(x = reorder(country, percentage), y = percentage, color = communist)) +
  geom_point() +
  facet_wrap(~health_decision_maker) +
    scale_x_reordered() +
    theme_linedraw() +
    theme(panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey"),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(color = "grey", fill = NA)) +
    theme(axis.text.x = element_text(angle = 30)) +
     labs(title = "Who gets to decide a woman's healthcare?", 
          x = "Countries", 
          y = "Percentage of Women whose healtcare is decided", 
          caption = "\n  \n Source: Inter-Parliamentary Union", 
          fill = "Been Communist?") 

```

